//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test5._0.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test5._0.Resources.I18NTest", typeof(I18NTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string GenericCrud_ClosePopup {
            get {
                return ResourceManager.GetString("GenericCrud.ClosePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string GenericCrud_Delete_Subtitle {
            get {
                return ResourceManager.GetString("GenericCrud.Delete.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string GenericCrud_Details_Subtitle {
            get {
                return ResourceManager.GetString("GenericCrud.Details.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GenericCrud_Edit_Subtitle {
            get {
                return ResourceManager.GetString("GenericCrud.Edit.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information stored successful..
        /// </summary>
        public static string GenericCrud_Index_CreateSuccessMessage {
            get {
                return ResourceManager.GetString("GenericCrud.Index.CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information deleted successful..
        /// </summary>
        public static string GenericCrud_Index_DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("GenericCrud.Index.DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data.
        /// </summary>
        public static string GenericCrud_Index_Subtitle {
            get {
                return ResourceManager.GetString("GenericCrud.Index.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new {0}.
        /// </summary>
        public static string GenericCrud_List_Create_Caption {
            get {
                return ResourceManager.GetString("GenericCrud.List.Create.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string GenericCrud_List_Create_Text {
            get {
                return ResourceManager.GetString("GenericCrud.List.Create.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the {0}.
        /// </summary>
        public static string GenericCrud_List_Delete_Caption {
            get {
                return ResourceManager.GetString("GenericCrud.List.Delete.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GenericCrud_List_Delete_Text {
            get {
                return ResourceManager.GetString("GenericCrud.List.Delete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the {0}.
        /// </summary>
        public static string GenericCrud_List_Details_Caption {
            get {
                return ResourceManager.GetString("GenericCrud.List.Details.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string GenericCrud_List_Details_Text {
            get {
                return ResourceManager.GetString("GenericCrud.List.Details.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the {0}.
        /// </summary>
        public static string GenericCrud_List_Edit_Caption {
            get {
                return ResourceManager.GetString("GenericCrud.List.Edit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GenericCrud_List_Edit_Text {
            get {
                return ResourceManager.GetString("GenericCrud.List.Edit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GenericCrud_List_GoBack_Caption {
            get {
                return ResourceManager.GetString("GenericCrud.List.GoBack.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GenericCrud_List_Index_Text {
            get {
                return ResourceManager.GetString("GenericCrud.List.Index.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string GenericCrud_List_Save_Caption {
            get {
                return ResourceManager.GetString("GenericCrud.List.Save.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GenericCrud_List_Save_Text {
            get {
                return ResourceManager.GetString("GenericCrud.List.Save.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the data. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string GenericCrud_UnableDeleteMessage {
            get {
                return ResourceManager.GetString("GenericCrud.UnableDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string GenericCrud_UnableSaveChangesMessage {
            get {
                return ResourceManager.GetString("GenericCrud.UnableSaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Genre
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
    }
}
